name: Deploy React App with CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Install CDK dependencies
        run: |
          cd cdk
          npm ci

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::890396755250:role/GitHubActionsCDKDeployRole
          aws-region: eu-central-1

      - name: Deploy with CDK
        run: |
          cd cdk
          npx cdk deploy --require-approval never --all
